name: test-deploy

on:
  push:
    branches: [ master ]


jobs:
  build:
  
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
     
     # convert notebook to python
     - name: Install nbconvert
       run: |
        python -m pip install --upgrade pip
        pip install nbconvert
     - name: Convert notebook
        run: jupyter nbconvert --to python etl_test.ipynb
        
     - name: Upload python script
        uses: actions/upload-artifact@v2
        with:
          name: etl_test.py
          path: etl_test.py
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download python script from build
        uses: actions/download-artifact@v2
        with:
          name: etl_test.py
          

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          

      - name: Set up AWS credentials
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          echo "[default]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" > ~/.aws/credentials
          

      - name: Upload to S3
        run: aws s3 cp traffic.py s3://${{secrets.S3_BUCKET}}/traffic_${GITHUB_SHA}.py --region us-east-1
      

      - name: Update Glue job
        run: |
          aws glue update-job --job-name "ETL TEST" --job-update \
            "Role=AWSGlueServiceRole-ETLTestCrawler,Command={Name=glueetl,ScriptLocation=s3://${{secrets.S3_BUCKET}}/traffic_${GITHUB_SHA}.py},Connections={Connections=redshift}" \
            --region us-east-1
      

      - name: Cleanup
        run: rm -rf ~/.aws
